spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driverClassName: org.postgresql.Driver
    hikari:
      schema: pcam
  batch:
    job:
      enabled: false
    initialize-schema: always
    hikari:
      maximum-pool-size: 500
      connection-timeout: 120000
      idle-timeout: 600000
      max-lifetime: 2000000
      leak-detection-threshold: 1200000
      pool-name: PreferenceDBPool
      validation-timeout: 60000
  jpa:
    properties:
      hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
  jdbc:
    batch-size: 25
  application:
    name: preference-batch
#  h2:
#    console:
#      enabled: false
cron:
  job:
    hybrisIngestion: 0 45 9 * * ?
    crmIngestion: 0 30 22 * * ?
    fbsfmcIngestion: 0 0 3 * * ?
    ingestSFMCOutlookUnsubscribed: 0 20 2 ? * FRI
    sendPreferencesToCRM: 0 0 18 * * ?
    sendPreferencesToCitiSuppresion: 0 40 17 ? * SUN
    sendPreferencesToInternalDestination: 0 0 10 ? * MON
    sendWeeklyLoyaltyComplaintToSource: 0 0 10 ? * SUN
    sendPreferencesToFlexInternalDestination: 0 0 18 * * ?
server:
  port: 8080

feign:
  retry:
    period: 3000
    maxPeriod: 3000
    maxAttempts: 3
  restapi:
    baseurl: http://localhost:8081/hdpc/v1/

#
inbound:
  files:
     registration: OPTIN_STANDARD_FLEX_
     registrationFbSfmc: OPTIN_STANDARD_FLEX_GCFB_
     sfmcUnsubscribedOutlook: ET.CAN.

outbound:
  files:
    complaintWeekly: LOYALTY_COMPLIANT_FILE_YYYYMMDD.csv.gz
    compliant: LOYALTY_DAILY_COMPLIANT.YYYYMMDD.txt.AXCOI.ZZAX
    internalCa: CA_COMPLIANT_FILE_YYYYMMDD.csv
    internalGarden: GARDEN_CLUB_COMPLIANT_FILE_YYYYMMDD.csv
    internalMover: NEW_MOVER_COMPLIANT_FILE_YYYYMMDD.csv
    flexAttributes: FLXEMCDADYYYYMMDDTHHMISS.CEACI.ZZAX
  citi:
    mastersuppresion: THDIN_THDDNS_MASTER_SUPPRESSION_YYYYMMDD.txt.pgp
  salesforce:
    extract: ET_YYYYMMDD.TXT.PGP


folders:
  inbound: inbound/
  error: error/
  processed: processed/
  outbound: outbound/
  crm:
    path: crm/
  fb-sfmc:
    path: fb-sfmc/
  hybris:
    path: hybris/
  sfmc:
    path: sfmc/
  citi:
    path:
  internal:
    path:
  salesforce:
    path:
  loyaltyCompliant:
    path:
  flexAttributes:
    path:

validation:
  extension: .txt.AXOSTD|.TXT.THD.txt.gpg|.pgp|.txt|.TXT
  email: ^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$

preference:
  centre:
    chunk: 100
    layoutb:
      chunk: 20
    layoutc:
      chunk: 10
    outboundCRM:
      chunk: 10
    outboundCiti:
      chunk: 20
    outboundInternal:
      chunk: 20
    outboundSalesforce:
      chunk: 20
    outboundLoyalty:
      chunk: 20
    outboundFlexAttributes:
      chunk: 20

gcp:
  project-id: np-cadotcom
  bucket:
    name: commsvc-preference-centre-feeds
    url: gs://commsvc-preference-centre-feeds