spring:
  #  datasource:
  #    url:
  #    username:
  #    password:
  #    driverClassName: org.postgresql.Driver
  #  jpa:
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: product-notification
#  h2:
#    console:
#      enabled: false
server:
  port: 8080

service:
  preference:
    baseurl: localhost:8081/hdpc/v1/

shelflife:
  bisn:
    purge:
      days: 180
email:
  pubsub-topic: custcomm-email
  en:
    template:
    subject:
  fr:
    template:
    subject:
  domain:
    environment:
analytics:
  bisn:
    purge:
      days: 2

inventory:
  bisn:
    purge:
      days: 1

feign:
  retry:
    period: 3000
    maxPeriod: 3000
    maxAttempts: 3

product:
  domain:
  web-url: /homedepotcacommercewebservices/v2/homedepotca

analytic:
  file:
    registration: registration
    email: emailanalytics
    bucket:
    path:

process:
  analytics:
    chunk: 100

sub:
  activity:
    days: 1
       