spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  batch:
    job:
      enabled: false
    initialize-schema: always
    hikari:
      maximum-pool-size: 500
      connection-timeout: 120000
      idle-timeout: 600000
      max-lifetime: 2000000
      leak-detection-threshold: 1200000
      pool-name: PreferenceDBPool
      validation-timeout: 60000
  jpa:
    properties:
      hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
  jdbc:
    batch-size: 25
  application:
    name: preference-batch
#  h2:
#    console:
#      enabled: false
cron:
  job:
    hybrisIngestion: 30 * * * * *
    crmIngestion: 30 * * * * *
    fbsfmcIngestion: 30 * * * * *
    ingestSFMCOutlookUnsubscribed: 30 * * * * *

server:
  port: 8080

service:
  preference:
    baseurl: http://localhost:8081/hdpc/v1/

feign:
  retry:
    period: 3000
    maxPeriod: 3000
    maxAttempts: 3
  restapi:
    baseurl: http://localhost:8081/hdpc/v1/

#
inbound:
  files:
     registration: OPTIN_STANDARD_FLEX_
     registrationFbSfmc: OPTIN_STANDARD_FLEX_GCFB_
     sfmcUnsubscribedOutlook: ET.CAN.

folders:
   inbound: \INBOUND\
   error: \ERROR\
   processed: \PROCESSED\
   crm:
     path: C:\batchFiles\CRM
   fb-sfmc:
     path: C:\batchFiles\FB-SFMC
   hybris:
     path: C:\batchFiles\Hybris
   sfmc:
     path: C:\batchFiles\SFMC

validation:
  extension: .txt.AXOSTD|.TXT.THD.txt.gpg|.pgp|.txt|.TXT
  email: ^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$

preference:
  centre:
    chunk: 100
    layoutb:
      chunk: 20
    layoutc:
      chunk: 10