spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  batch:
    job:
      enabled: false
    initialize-schema: always
    hikari:
      maximum-pool-size: 500
      connection-timeout: 120000
      idle-timeout: 600000
      max-lifetime: 2000000
      leak-detection-threshold: 1200000
      pool-name: PreferenceDBPool
      validation-timeout: 60000
  jpa:
    properties:
      hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
  jdbc:
    batch-size: 25
  application:
    name: preference-batch
#  h2:
#    console:
#      enabled: false
cron:
  job:
    registration: 30 * * * * *
    ingestSFMC: 30 * * * * *

server:
  port: 8080

service:
  preference:
    baseurl: http://localhost:8081/hdpc/v1/

shelflife:
  bisn:
    purge:
      days: 180
email:
  pubsub-topic: custcomm-email
  en:
    template:
    subject:
  fr:
    template:
    subject:
  domain:
    environment:
analytics:
  bisn:
    purge:
      days: 1

inventory:
  bisn:
    purge:
      days: 1

feign:
  retry:
    period: 3000
    maxPeriod: 3000
    maxAttempts: 3

product:
  domain:
  web-url: /homedepotcacommercewebservices/v2/homedepotca

analytic:
  file:
    registration: registration
    email: emailanalytics
    bucket:
    path:

inbound:
  source:
    path: C:\batchFiles\
    folder:
      inbound: INBOUND
      error: ERROR
      processed: PROCESSED
  file:
    registration: OPTIN_STANDARD_FLEX_YYYYMMDD.txt
    ingestSFMC: ET.CAN.YYYYMMDD.TXT

process:
  analytics:
    chunk: 100

sub:
  activity:
    days: 1