spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driverClassName: org.postgresql.Driver
    hikari:
      schema: pcam
  batch:
    job:
      enabled: false
    initialize-schema: always
    hikari:
      maximum-pool-size: 500
      connection-timeout: 120000
      idle-timeout: 600000
      max-lifetime: 2000000
      leak-detection-threshold: 1200000
      pool-name: PreferenceDBPool
      validation-timeout: 60000
  jpa:
    properties:
      hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
  jdbc:
    batch-size: 25
  application:
    name: preference-batch
  jackson:
    time-zone: America/New_York
#  h2:
#    console:
#      enabled: false
process: citiOut
exitAfter: true
cron:
  job:
    hybrisIngestion: 0 30 22 * * ?
    crmIngestion: 0 30 22 * * ?
    fbsfmcIngestion: 0 0 3 * * ?
    ingestSFMCOutlookUnsubscribed: 0 30 22 * * ?
    sendPreferencesToCRM: 0 30 22 * * ?
    sendPreferencesToCitiSuppresion: 0 30 22 * * ?
    sendPreferencesToInternalDestination: 0 0 10 ? * MON
    sendWeeklyLoyaltyComplaintToSource: 0 0 10 ? * SUN
    sendPreferencesToFlexInternalDestination: 0 0 18 * * ?
    sendPreferencesToSFMC: 0 0 18 * * ?
    createDailyCountReport: 0 0 7 * * ?
    individualProcess: 30 * * * * *
server:
  port: 8081

feign:
  retry:
    period: 3000
    maxPeriod: 3000
    maxAttempts: 3
  restapi:
    baseurl: http://127.0.0.1:8080/hdpc/v1/

#
inbound:
  files:
     registration: OPTIN_STANDARD_FLEX_
     registrationFbSfmc: OPTIN_STANDARD_FLEX_GCFB_
     sfmcUnsubscribedOutlook: ET.CAN.

outbound:
  files:
    dailycountreport: pcam_daily_count_report_YYYYMMDD.csv
    complaintWeekly: LOYALTY_COMPLIANT_FILE_YYYYMMDD.csv.gz
    compliant: LOYALTY_DAILY_COMPLIANT.YYYYMMDD.txt.AXCOI.ZZAX
    internalCa: CA_COMPLIANT_FILE_YYYYMMDD.csv
    internalGarden: GARDEN_CLUB_COMPLIANT_FILE_YYYYMMDD.csv
    internalMover: NEW_MOVER_COMPLIANT_FILE_YYYYMMDD.csv
    flexAttributes: FLXEMCDADYYYYMMDDTHHMISS.CEACI.ZZAX
  citi:
    mastersuppresion: THDIN_THDDNS_MASTER_SUPPRESSION_YYYYMMDD.txt.pgp
  salesforce:
    extract: ET_YYYYMMDD.TXT.PGP

folders:
  inbound: inbound/
  error: error/
  processed: processed/
  outbound: outbound/
  crm:
    path: crm/
  fb-sfmc:
    path: fb-sfmc/
  hybris:
    path: hybris/
  sfmc:
    path: sfmc/
  citi:
    path: outbound/citi/
  internal:
    path:
  salesforce:
    path:
  loyaltyCompliant:
    path:
  flexAttributes:
    path:

validation:
  extension: .txt.AXOSTD|.TXT.THD.txt.gpg|.pgp|.txt|.TXT|.TXT.THD.txt|.THD
  email: ^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$

preference:
  centre:
    chunk: 100
    layoutb:
      chunk: 20
    layoutc:
      chunk: 10
    outboundCRM:
      chunk: 10
    outboundCiti:
      chunk: 20
    outboundInternal:
      chunk: 20
    outboundSalesforce:
      chunk: 20
    outboundLoyalty:
      chunk: 20
    outboundFlexAttributes:
      chunk: 20
    dailyCountReport:
      chunk: 5

gcp:
  project-id: np-cadotcom
  bucket:
    name: commsvc-preference-centre-feeds
    url: gs://commsvc-preference-centre-feeds

logging:
  level:
    ca.homedepot.preference: INFO
    root: ERROR
    org:
      hibernate: INFO
      springframework: INFO

version: PCAM-433 Citi trim over all columns

notification:
  eventId: 5001
  inbound:
    hybris:
      email: HDCA_online_operations@homedepot.com,shirin_khoja@homedepot.com,jennifer_luo@homedepot.com,abida_savani@homedepot.com
      name: HDCA Operations,Shirin Khoja,Jennifer Luo,Abida Savani
      subject: Hybrids Inbound Notification Email
      fromEmail: No-reply@homedepot.com
      eventName: hybridsNotification
      eventDefinition: pcamNotification
      source: pcam
    SFMC:
      email: nishi_bagaria@homedepot.com,VENKATA_SESHA_SAI_BHARATH_MANNAVA@homedepot.com,shirin_khoja@homedepot.com,jennifer_luo@homedepot.com,abida_savani@homedepot.com
      name: Nishi Bagaria,Venkata Mannava,Shirin Khoja,Jennifer Luo,Abida Savani
      subject: SFMC Inbound Notification Email
      fromEmail: No-reply@homedepot.com
      eventName: hybridsNotification
      eventDefinition: pcamNotification
      source: pcam
  outbound:
    CRM:
      email: biravi_sivanesan@homedepot.com,ashley_d_rosenberg@homedepot.com,shirin_khoja@homedepot.com,jennifer_luo@homedepot.com,abida_savani@homedepot.com
      name: Biravi Sivanesan,Ashley Rosenberg,Shirin Khoja,Jennifer Luo,Abida Savani
      subject: CRM Outbound Notification Email
      fromEmail: No-reply@homedepot.com
      eventName: hybridsNotification
      eventDefinition: pcamNotification
      source: pcam
    SFMC:
      email: nishi_bagaria@homedepot.com,VENKATA_SESHA_SAI_BHARATH_MANNAVA@homedepot.com,shirin_khoja@homedepot.com,jennifer_luo@homedepot.com,abida_savani@homedepot.com
      name: Nishi Bagaria,Venkata Mannava,Shirin Khoja,Jennifer Luo,Abida Savani
      subject: SFMC Outbound Notification Email
      fromEmail: No-reply@homedepot.com
      eventName: hybridsNotification
      eventDefinition: pcamNotification
      source: pcam
    citi:
      email: crs.nam.cards.canada.it@citi.com,nelson.olarte@citi.com,maria.scott@citi.com,sengodi.selvi.d@citi.com,shirin_khoja@homedepot.com,jennifer_luo@homedepot.com,abida_savani@homedepot.com
      name: Canada Citi,Nelson Olarte,Maria Scott,Sengodi Selvi,Shirin Khoja,Jennifer Luo,Abida Savani
      subject: Citi Outbound Notification Email
      fromEmail: No-reply@homedepot.com
      eventName: hybridsNotification
      eventDefinition: pcamNotification
      source: pcam
